fix(tokens): change default danger token
juntossomosmais/atomium pull request #291
Opened 2023-10-19 15:25 UTC by SallesCosta

## Infos

[Task](https://juntossomosmais.monday.com/boards/XXX/pulses/XXX)

#### What is being delivered?

Simple color adjustment. The `danger` color will now be `var(--color-contextual-error-light-1)` instead of a default ionic color.

#### What impacts?

Nothing.

#### Reversal plan

Rollback this PR.

#### Evidences

![Captura de Tela 2023-10-19 às 17 20 28](https://github.com/juntossomosmais/atomium/assets/81476236/95ffda3a-238a-42f4-8033-aad25807ae28)

2023-10-19 23:24 UTC, gabrielduete submitted a review, later dismissed

2023-10-20 14:48 UTC, felipefialho requested changes

2023-10-20 14:48 UTC, felipefialho commented on packages/core/src/global/global.scss
>    --ion-color-danger-rgb: var(--color-contextual-danger-regular-rgb);
We need to change `rgb` too

```suggestion
  --ion-color-danger-rgb: var(--color-contextual-error-light-1-rgb);
```

2023-10-20 18:29 UTC, gabrielduete approved these changes

2023-10-20 19:31 UTC, felipefialho approved these changes

2023-10-20 19:47 UTC, luiz-ortega approved these changes

2023-10-20 19:58 UTC, mauriciomutte approved these changes

2023-10-21 00:27 UTC, RodrigoRVSN approved these changes

2023-10-23 11:28 UTC, merged